### ISSUE TITLE
new RestrictImports rule results in stack over flow

### ISSUE THREAD

**Issue by bertramn** [skuzzle/restrict-imports-enforcer-rule#21]
Recently tried to upgrade from 0.8.0 to 0.13.0 but a configuration like below will result in a StackOverflowError. I used the new `RestrictImports` classes as per deprecation warning and it all went south from there. Hope this is sufficient information to look into this problem.

The last known working version with the old `de.skuzzle.enforcer.restrictimports.RestrictImports` is 0.10.0, even if I go to version 0.11.0 with the old rules I get the same error as below.

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-enforcer-plugin</artifactId>
  <executions>
    <execution>
      <id>enforce-versions</id>
      <goals>
        <goal>enforce</goal>
      </goals>
      <configuration>
        <rules>
          <requireMavenVersion>
            <version>3.3.0</version>
          </requireMavenVersion>
          <requireJavaVersion>
            <version>1.8</version>
          </requireJavaVersion>
        </rules>
      </configuration>
    </execution>
    <execution>
      <id>check-jaxb-generated-imports</id>
      <goals>
        <goal>enforce</goal>
      </goals>
      <phase>compile</phase>
      <configuration>
        <rules>
          <restrictImports implementation="de.skuzzle.enforcer.restrictimports.rule.RestrictImports">
            <reason>JAXBElement is banned from the domain model, see design principles.</reason>
            <bannedImport>javax.xml.bind.JAXBElement</bannedImport>
            <exclusion>my.model.ObjectFactory</exclusion>
          </restrictImports>
          <restrictImports implementation="de.skuzzle.enforcer.restrictimports.rule.RestrictImports">
            <reason>Dates have to be mapped to Joda or Java Time</reason>
            <bannedImport>javax.xml.datatype.XMLGregorianCalendar</bannedImport>
            <includeTestCode>true</includeTestCode>
          </restrictImports>
        </rules>
      </configuration>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>de.skuzzle.enforcer</groupId>
      <artifactId>restrict-imports-enforcer-rule</artifactId>
      <version>0.13.0</version>
    </dependency>
  </dependencies>
</plugin>
```

Results in:

```
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (check-jaxb-generated-imports) @ my-model ---
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-enforcer-plugin:1.4.1, parent: sun.misc.Launcher$AppClassLoader@55f96302]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce' with basic configurator -->
[DEBUG]   (s) fail = true
[DEBUG]   (s) failFast = false
[DEBUG]   (f) ignoreCache = false
[DEBUG]   (f) mojoExecution = org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce {execution: check-jaxb-generated-imports}
[DEBUG]   (s) project = MavenProject: com.example:my-model:3.0.14-SNAPSHOT @ /Users/fred/workspaces/my-model/pom.xml
[DEBUG]   (s) reason = JAXBElement is banned from the domain model, see design principles.
[DEBUG]   (s) bannedImport = javax.xml.bind.JAXBElement
[DEBUG]   (s) exclusion = my.model.ObjectFactory
[DEBUG]   (s) reason = Dates have to be mapped to Joda or Java Time
[DEBUG]   (s) bannedImport = javax.xml.datatype.XMLGregorianCalendar
[DEBUG]   (s) includeTestCode = true
[DEBUG]   (s) rules = [de.skuzzle.enforcer.restrictimports.rule.RestrictImports@16088b32, de.skuzzle.enforcer.restrictimports.rule.RestrictImports@2f3b4de2]
[DEBUG]   (s) session = org.apache.maven.execution.MavenSession@7885776b
[DEBUG]   (s) skip = false
[DEBUG] -- end configuration --
[DEBUG] Executing rule: de.skuzzle.enforcer.restrictimports.rule.RestrictImports
[DEBUG] Checking for banned imports
[DEBUG] Banned import groups:
BannedImportGroup{basePackages=[**], bannedImports=[javax.xml.bind.JAXBElement], allowedImports=[], excludedClasses=[my.model.ObjectFactory], reason=JAXBElement is banned from the domain model, see design principles.}
[DEBUG] Including source dir: /Users/fred/workspaces/my-model/src/main/java
[DEBUG] Including source dir: /Users/fred/workspaces/my-model/target/generated-sources/xjc
[DEBUG] Including source dir: /Users/fred/workspaces/my-model/target/generated-sources/annotations
[DEBUG] Analyzer settings:
AnalyzerSettings{sourceFileCharset=UTF-8, commentLineBufferSize=128, rootDirectories=[/Users/fred/workspaces/my-model/src/main/java, /Users/fred/workspaces/my-model/target/generated-sources/xjc, /Users/fred/workspaces/my-model/target/generated-sources/annotations]}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.731 s
[INFO] Finished at: 2018-11-06T00:58:20+10:00
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/local/Cellar/maven/3.5.4/libexec/conf/logging/
constituent[1]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-repository-metadata-3.5.4.jar
constituent[2]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-resolver-transport-wagon-1.1.1.jar
constituent[3]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/aopalliance-1.0.jar
constituent[4]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-resolver-provider-3.5.4.jar
constituent[5]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/plexus-utils-3.1.0.jar
constituent[6]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/plexus-interpolation-1.24.jar
constituent[7]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-artifact-3.5.4.jar
constituent[8]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/plexus-cipher-1.7.jar
constituent[9]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/guava-20.0.jar
constituent[10]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-slf4j-provider-3.5.4.jar
constituent[11]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/slf4j-api-1.7.25.jar
constituent[12]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/cdi-api-1.0.jar
constituent[13]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/jcl-over-slf4j-1.7.25.jar
constituent[14]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-resolver-spi-1.1.1.jar
constituent[15]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-compat-3.5.4.jar
constituent[16]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-plugin-api-3.5.4.jar
constituent[17]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/plexus-sec-dispatcher-1.4.jar
constituent[18]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-resolver-util-1.1.1.jar
constituent[19]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/plexus-component-annotations-1.7.1.jar
constituent[20]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-settings-builder-3.5.4.jar
constituent[21]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/commons-cli-1.4.jar
constituent[22]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/commons-io-2.5.jar
constituent[23]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/jansi-1.17.1.jar
constituent[24]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-core-3.5.4.jar
constituent[25]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-resolver-impl-1.1.1.jar
constituent[26]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/guice-4.2.0-no_aop.jar
constituent[27]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/org.eclipse.sisu.inject-0.3.3.jar
constituent[28]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/wagon-file-3.1.0.jar
constituent[29]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-builder-support-3.5.4.jar
constituent[30]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-model-3.5.4.jar
constituent[31]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-settings-3.5.4.jar
constituent[32]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/wagon-http-3.1.0-shaded.jar
constituent[33]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-resolver-api-1.1.1.jar
constituent[34]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-resolver-connector-basic-1.1.1.jar
constituent[35]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-shared-utils-3.2.1.jar
constituent[36]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/org.eclipse.sisu.plexus-0.3.3.jar
constituent[37]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-model-builder-3.5.4.jar
constituent[38]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/javax.inject-1.jar
constituent[39]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/maven-embedder-3.5.4.jar
constituent[40]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/jsr250-api-1.0.jar
constituent[41]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/commons-lang3-3.5.jar
constituent[42]: file:/usr/local/Cellar/maven/3.5.4/libexec/lib/wagon-provider-api-3.1.0.jar
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
```

**Comment by skuzzle** [comment]
That looks funny. Do you happen to have a larger part of the stack trace? I suspect this has something to do with comment line recognition. I'll look into it

**Comment by skuzzle** [comment]
I have deployed `0.14.0-SNAPSHOT`. Could you try to reproduce your issue with that version? It also contains some more log statements that should allow us to find out on which file it breaks in case it still happens

**Comment by skuzzle** [comment]
The changes I made were important enough to justify a non-snapshot release anyways, so you can go and test with version `0.14.0`. I'd still be interested in some more details about this problem so if you could provide a longer version of the stack trace which shows the origin that would be great.

**Comment by bertramn** [comment]
Sorry for late reply, was chasing something else lately. Yes I can confirm the extension is behaving now. Many thanks for fixing this issue.
