### ISSUE TITLE
Parent pom without source code makes the plugin crash

### ISSUE THREAD

**Issue by aandeers** [skuzzle/restrict-imports-enforcer-rule#3]
I have setup the plugin in a parent pom inherited by other poms but the plugin crashes as the parent pom has no source code. Stacktrace follows.

`Caused by: java.nio.file.NoSuchFileException: C:\..\Whatever\src\main\java
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
        at java.nio.file.Files.find(Files.java:3687)
        at de.skuzzle.enforcer.restrictimports.impl.IOUtilsImpl.listFiles(IOUtilsImpl.java:25)
        ... 35 more
[WARNING] Rule 0: de.skuzzle.enforcer.restrictimports.RestrictImports failed with message:
Encountered IO exception`

**Comment by aandeers** [comment]
When will the new version be available through the central repository?

**Comment by skuzzle** [comment]
I have just released the fix as version 0.6.0. It might take some time though until it is available from maven central (minutes to few hours).
I'd be happy if could test the version and report whether it now works as expected.

**Comment by aandeers** [comment]
The release is now available. I will try it out some time soon. Not that it matters but the release date is 1969! Have a look at https://mvnrepository.com/artifact/de.skuzzle.enforcer/restrict-imports-enforcer-rule :)

**Comment by skuzzle** [comment]
The release date thingy is funny. Might also be the reason why the maven badge doesn't update. I have no idea though why that happened.

**Comment by aandeers** [comment]
The bug fix worked out just fine. Thank you!
